version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/harsh.rtd.squareops.co.in
    overwrite: true

hooks:
 
  ApplicationStop:
    - location: script/stop.sh
      timeout: 300
      runas: root


  ApplicationStart:
    - location: script/start.sh
      timeout: 300
      runas: root
